## code to prepare `rt2` dataset goes here

# Simulated data generated by SPIC:
# mu3 = LATER 1 mu 3 sig 0.5 R, count = 200
# mu4 = LATER 2 mu 4 sig 0.5 R, count = 200
df <- as.data.frame(dplyr::tribble(
~times, ~raw, ~name,
180,  1, "mu4",
200,  5, "mu4",
210,  9, "mu4",
220, 10, "mu4",
230, 19, "mu4",
240, 23, "mu4",
250, 34, "mu4",
260, 15, "mu4",
270, 28, "mu4",
280, 14, "mu4",
290, 13, "mu4",
300, 11, "mu4",
310,  3, "mu4",
320,  7, "mu4",
330,  1, "mu4",
340,  1, "mu4",
350,  1, "mu4",
370,  1, "mu4",
380,  1, "mu4",
390,  2, "mu4",
430,  1, "mu4",
240,  1, "mu3",
250,  2, "mu3",
260,  1, "mu3",
270,  8, "mu3",
280, 11, "mu3",
290,  8, "mu3",
300, 16, "mu3",
310, 11, "mu3",
320, 13, "mu3",
330, 21, "mu3",
340, 12, "mu3",
350, 15, "mu3",
360, 12, "mu3",
370, 13, "mu3",
380,  9, "mu3",
390, 10, "mu3",
400,  7, "mu3",
410,  6, "mu3",
420,  2, "mu3",
430,  6, "mu3",
440,  3, "mu3",
450,  3, "mu3",
460,  1, "mu3",
470,  2, "mu3",
480,  1, "mu3",
490,  3, "mu3",
500,  1, "mu3",
520,  1, "mu3",
530,  1, "mu3"
))

rt2 <- df[rep(1:nrow(df), df[,2]), -2]

rt2 <- dplyr::mutate(
  rt2,
  name = factor(name),
  color = factor(dplyr::case_when(name == "mu3" ~ "#1B9E77", name == "mu4" ~ "#D95F02"))
)

usethis::use_data(rt2, overwrite = TRUE)
